In [120]:
import numpy as np
import pandas as pd
import glob
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import roc_curve, auc
import sklearn
from time import time
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import classification_report
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import plotly.express as px


In [121]:
dos_df = pd.read_csv('/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/DoS-SYN_Flood7.csv')
dos_df['label']='DoS'
dos_df

ts  flow_duration  Header_Length  Protocol Type  Duration  \
0        1.659719e+09       0.000000           54.0            6.0      64.0   
1        1.659719e+09       0.000000           54.0            6.0      64.0   
2        1.659719e+09       0.000000           54.0            6.0      64.0   
3        1.659719e+09       0.000000           54.8            6.0      64.0   
4        1.659719e+09       0.000000           57.2            6.0      64.0   
...               ...            ...            ...            ...       ...   
2058579  1.659719e+09       5.509033          108.0            6.0      64.0   
2058580  1.659719e+09       5.509336          108.0            6.0      64.0   
2058581  1.659719e+09       5.505791          108.0            6.0      64.0   
2058582  1.659719e+09       5.497996          108.0            6.0      64.0   
2058583  1.659719e+09       5.498243          108.0            6.0      64.0   

             Rate     Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0        0.000000  0.000000    0.0              0.0              1.0  ...   
1        0.000000  0.000000    0.0              0.0              1.0  ...   
2        0.000000  0.000000    0.0              0.0              1.0  ...   
3        0.000000  0.000000    0.0              0.0              0.9  ...   
4        0.000000  0.000000    0.0              0.0              1.0  ...   
...           ...       ...    ...              ...              ...  ...   
2058579  0.363040  0.363040    0.0              0.0              1.0  ...   
2058580  0.363020  0.363020    0.0              0.0              1.0  ...   
2058581  0.363254  0.363254    0.0              0.0              1.0  ...   
2058582  0.363769  0.363769    0.0              0.0              1.0  ...   
2058583  0.363753  0.363753    0.0              0.0              1.0  ...   

         Covariance  Variance      Weight  DS status  Fragments  \
0          0.000000       0.0   38.500000        0.0        0.0   
1          0.000000       0.0  244.600000        0.0        0.0   
2          0.000000       0.0   38.500000        0.0        0.0   
3          0.159557       0.2  244.600000        0.0        0.0   
4          0.414025       0.2   38.500000        0.0        0.0   
...             ...       ...         ...        ...        ...   
2058579    0.000000       0.0  244.600000        0.0        0.0   
2058580    0.000000       0.0   38.500000        0.0        0.0   
2058581    0.000000       0.0  244.600000        0.0        0.0   
2058582    0.000000       0.0   38.500000        0.0        0.0   
2058583    0.000000       0.0  185.166667        0.0        0.0   

         Sequence number  Protocol Version  flow_idle_time  flow_active_time  \
0                    0.0               0.0    1.659719e+09          0.000000   
1                    0.0               0.0    1.659719e+09          0.000000   
2                    0.0               0.0    1.659719e+09          0.000000   
3                    0.0               0.0    1.659719e+09          0.000000   
4                    0.0               0.0    1.659719e+09          0.000000   
...                  ...               ...             ...               ...   
2058579              0.0               0.0    5.509033e+00          5.509033   
2058580              0.0               0.0    5.509336e+00          5.509336   
2058581              0.0               0.0    5.505791e+00          5.505791   
2058582              0.0               0.0    5.497996e+00          5.497996   
2058583              0.0               0.0    5.498243e+00          5.498243   

         label  
0          DoS  
1          DoS  
2          DoS  
3          DoS  
4          DoS  
...        ...  
2058579    DoS  
2058580    DoS  
2058581    DoS  
2058582    DoS  
2058583    DoS  

[2058584 rows x 63 columns]

In [122]:
miriai_df = pd.read_csv('/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/Mirai-udpplain24.csv')
miriai_df['label']='Mirai'
miriai_df

ts  flow_duration  Header_Length  Protocol Type  Duration  \
0       1.676396e+09       0.013632         2002.9           15.3      57.6   
1       1.676396e+09       0.068589         7479.0           17.0      64.0   
2       1.676396e+09       0.069178        13019.0           17.0      64.0   
3       1.676396e+09       0.069870        18559.0           17.0      64.0   
4       1.676396e+09       0.070690        24099.0           17.0      64.0   
...              ...            ...            ...            ...       ...   
150437  1.675787e+09       4.288545      5844977.0           17.0      64.0   
150438  1.675787e+09       3.864644      5265224.3           17.0      64.0   
150439  1.675787e+09       4.301104      5855503.0           17.0      64.0   
150440  1.675787e+09       4.403413      2642524.6           17.0      64.0   
150441  1.675787e+09       4.429043      1840942.0           17.0      64.0   

                 Rate          Srate  Drate  fin_flag_number  syn_flag_number  \
0       850091.118241  850091.118241    0.0              0.0              0.0   
1          196.693380     196.693380    0.0              0.0              0.0   
2          339.594674     339.594674    0.0              0.0              0.0   
3          479.364449     479.364449    0.0              0.0              0.0   
4          615.234898     615.234898    0.0              0.0              0.0   
...               ...            ...    ...              ...              ...   
150437    2460.158095    2460.158095    0.0              0.0              0.0   
150438    2459.501543    2459.501543    0.0              0.0              0.0   
150439    2457.392424    2457.392424    0.0              0.0              0.0   
150440    1091.083089    1091.083089    0.0              0.0              0.0   
150441     750.274937     750.274937    0.0              0.0              0.0   

        ...    Covariance  Variance  Weight  DS status  Fragments  \
0       ...  15062.367578       0.4    38.5        0.0        0.0   
1       ...  26825.274254       1.0   244.6        0.0        0.0   
2       ...      0.000000       0.0    38.5        0.0        0.0   
3       ...      0.000000       0.0   244.6        0.0        0.0   
4       ...      0.000000       0.0    38.5        0.0        0.0   
...     ...           ...       ...     ...        ...        ...   
150437  ...      0.000000       0.0   244.6        0.0        0.0   
150438  ...  12411.522568       0.5    38.5        0.0        0.0   
150439  ...  13859.236651       1.0   244.6        0.0        0.0   
150440  ...      0.000000       0.0    38.5        0.0        0.0   
150441  ...      0.000000       0.0   121.0        0.0        0.0   

        Sequence number  Protocol Version  flow_idle_time  flow_active_time  \
0                   0.0               0.0    3.352792e+08          0.013632   
1                   0.0               0.0    6.730556e-05          0.068589   
2                   0.0               0.0    5.960464e-05          0.069178   
3                   0.0               0.0    7.519722e-05          0.069870   
4                   0.0               0.0    8.409023e-05          0.070690   
...                 ...               ...             ...               ...   
150437              0.0               0.0    5.090237e-05          4.288545   
150438              0.0               0.0    1.675787e+08          3.864644   
150439              0.0               0.0    1.764059e-04          4.301104   
150440              0.0               0.0    9.799480e-03          4.403413   
150441              0.0               0.0    9.298325e-05          4.429043   

        label  
0       Mirai  
1       Mirai  
2       Mirai  
3       Mirai  
4       Mirai  
...       ...  
150437  Mirai  
150438  Mirai  
150439  Mirai  
150440  Mirai  
150441  Mirai  

[150442 rows x 63 columns]

In [123]:
benign_df = pd.read_csv('/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/BenignTraffic3.csv')
benign_df['label']='Benign'
benign_df



ts  flow_duration  Header_Length  Protocol Type  Duration  \
0       1.665263e+09       0.006343         5339.3            7.1      97.6   
1       1.665263e+09       0.056789        11027.0            6.0     231.0   
2       1.665263e+09       0.123499         7420.3            6.0     132.4   
3       1.665263e+09       0.377002         8620.0            8.2     101.4   
4       1.665263e+09       0.578446        31073.2            6.0     147.5   
...              ...            ...            ...            ...       ...   
129827  1.665260e+09      22.361438      1411548.1            5.4      57.6   
129828  1.665260e+09      66.118434       217567.8            7.1      80.7   
129829  1.665260e+09      42.293080      1274433.4            6.0     164.2   
129830  1.665260e+09      41.623182         9858.2            6.0      64.0   
129831  1.665260e+09      41.316525         9913.8            6.0      64.0   

               Rate        Srate  Drate  fin_flag_number  syn_flag_number  \
0       2621.293559  2621.293559    0.0              0.0              0.0   
1        236.873204   236.873204    0.0              0.0              0.0   
2        145.661198   145.661198    0.0              0.0              0.0   
3         28.584979    28.584979    0.0              0.0              0.0   
4         56.100348    56.100348    0.0              0.0              0.0   
...             ...          ...    ...              ...              ...   
129827    59.055022    59.055022    0.0              0.0              0.0   
129828     9.208578     9.208578    0.0              0.2              0.0   
129829    53.082714    53.082714    0.0              0.1              0.0   
129830     0.876923     0.876923    0.0              0.1              0.0   
129831     0.914649     0.914649    0.0              0.2              0.0   

        ...    Covariance  Variance  Weight  DS status  Fragments  \
0       ...  9.258365e+04       0.3    38.5        0.0        0.0   
1       ...  4.880776e+05       1.0   244.6        0.0        0.0   
2       ...  3.951324e+05       0.9    38.5        0.0        0.0   
3       ...  5.232150e+05       1.0   244.6        0.0        0.0   
4       ...  6.465004e+05       0.9    38.5        0.0        0.0   
...     ...           ...       ...     ...        ...        ...   
129827  ...  1.058065e+06       1.0   244.6        0.0        0.0   
129828  ...  4.337437e+03       0.9    38.5        0.0        0.0   
129829  ...  2.019715e+04       1.0   244.6        0.0        0.0   
129830  ...  6.550540e+04       0.9    38.5        0.0        0.0   
129831  ...  6.245446e+04       1.0   171.0        0.0        0.0   

        Sequence number  Protocol Version  flow_idle_time  flow_active_time  \
0                   0.0               0.0    4.995788e+08          0.006343   
1                   0.0               0.0    3.777981e-04          0.056789   
2                   0.0               0.0    1.665263e+08          0.123499   
3                   0.0               0.0    3.330525e+08          0.377002   
4                   0.0               0.0    5.599618e-03          0.578446   
...                 ...               ...             ...               ...   
129827              0.0               0.0    9.868374e-01         22.361438   
129828              0.0               0.0    2.214067e+00         66.118434   
129829              0.0               0.0    1.772661e-02         42.293080   
129830              0.0               0.0    3.687060e-02         41.623182   
129831              0.0               0.0    3.671722e-02         41.316525   

         label  
0       Benign  
1       Benign  
2       Benign  
3       Benign  
4       Benign  
...        ...  
129827  Benign  
129828  Benign  
129829  Benign  
129830  Benign  
129831  Benign  

[129832 rows x 63 columns]

In [124]:
path = r'/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/torii' # use your path
all_files = glob.glob(path + "/*.csv")
li = []

for filename in all_files:
    df = pd.read_csv(filename)
    li.append(df)

torii_df = pd.concat(li, axis=0, ignore_index=True)
torii_df['label'] = 'Torii'

torii_df.head()



ts  flow_duration  Header_Length  Protocol Type  Duration  \
0  1.538573e+09       0.500837          128.1           13.6      51.2   
1  1.538573e+09       2.012274          219.0           13.6      51.2   
2  1.538573e+09       0.523727          128.4           13.6      51.2   
3  1.538573e+09       1.054326          145.2           15.3      57.6   
4  1.538573e+09       0.511880          128.7           11.9      44.8   

          Rate        Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0  1105.632893  1105.632893    0.0              0.0              0.0  ...   
1  1797.323164  1797.323164    0.0              0.0              0.0  ...   
2    15.801772    15.801772    0.0              0.0              0.0  ...   
3     9.143670     9.143670    0.0              0.0              0.0  ...   
4    75.601691    75.601691    0.0              0.0              0.0  ...   

   Covariance  Variance  Weight  DS status  Fragments  Sequence number  \
0  113.845668       0.9    38.5        0.0        0.0              0.0   
1  169.495456       1.0   244.6        0.0        0.0              0.0   
2   81.095402       0.9    38.5        0.0        0.0              0.0   
3   81.947047       1.0   244.6        0.0        0.0              0.0   
4  133.334614       0.9    38.5        0.0        0.0              0.0   

   Protocol Version  flow_idle_time  flow_active_time  label  
0               0.0    6.154292e+08          0.500837  Torii  
1               0.0    1.538573e+08          2.012274  Torii  
2               0.0    6.154292e+08          0.523727  Torii  
3               0.0    6.154292e+08          1.054326  Torii  
4               0.0    3.077146e+08          0.511880  Torii  

[5 rows x 63 columns]

In [125]:
print(dos_df.shape,
    miriai_df.shape,
    benign_df.shape, 
    torii_df.shape)

(2058584, 63) (150442, 63) (129832, 63) (10044, 63)


In [126]:
source_data = [
    dos_df,
    miriai_df,
    benign_df, 
    torii_df,
]

source_df = pd.concat(source_data)
source_df

ts  flow_duration  Header_Length  Protocol Type  Duration  \
0      1.659719e+09       0.000000   5.400000e+01            6.0      64.0   
1      1.659719e+09       0.000000   5.400000e+01            6.0      64.0   
2      1.659719e+09       0.000000   5.400000e+01            6.0      64.0   
3      1.659719e+09       0.000000   5.480000e+01            6.0      64.0   
4      1.659719e+09       0.000000   5.720000e+01            6.0      64.0   
...             ...            ...            ...            ...       ...   
10039  1.538565e+09   26555.406249   6.116214e+05            3.6      33.9   
10040  1.538565e+09   35421.791380   8.157976e+05            4.8      45.2   
10041  1.538565e+09   43752.761110   6.592080e+05            7.0      51.7   
10042  1.538565e+09   26586.712659   6.122694e+05            3.6      33.9   
10043  1.538565e+09   44323.986387   1.020804e+06            6.0      56.5   

           Rate     Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0      0.000000  0.000000    0.0              0.0              1.0  ...   
1      0.000000  0.000000    0.0              0.0              1.0  ...   
2      0.000000  0.000000    0.0              0.0              1.0  ...   
3      0.000000  0.000000    0.0              0.0              0.9  ...   
4      0.000000  0.000000    0.0              0.0              1.0  ...   
...         ...       ...    ...              ...              ...  ...   
10039  0.410148  0.410148    0.0              0.0              0.0  ...   
10040  0.410135  0.410135    0.0              0.0              0.0  ...   
10041  0.334197  0.334197    0.0              0.0              0.0  ...   
10042  0.410116  0.410116    0.0              0.0              0.0  ...   
10043  0.410128  0.410128    0.0              0.0              0.0  ...   

       Covariance  Variance      Weight  DS status  Fragments  \
0        0.000000       0.0   38.500000        0.0        0.0   
1        0.000000       0.0  244.600000        0.0        0.0   
2        0.000000       0.0   38.500000        0.0        0.0   
3        0.159557       0.2  244.600000        0.0        0.0   
4        0.414025       0.2   38.500000        0.0        0.0   
...           ...       ...         ...        ...        ...   
10039    4.615542       0.9  244.600000        0.0        0.0   
10040    4.946916       0.7   38.500000        0.0        0.0   
10041  119.371135       1.0  244.600000        0.0        0.0   
10042    7.595333       0.9   38.500000        0.0        0.0   
10043   67.524036       1.0  185.166667        0.0        0.0   

       Sequence number  Protocol Version  flow_idle_time  flow_active_time  \
0                  0.0               0.0    1.659719e+09          0.000000   
1                  0.0               0.0    1.659719e+09          0.000000   
2                  0.0               0.0    1.659719e+09          0.000000   
3                  0.0               0.0    1.659719e+09          0.000000   
4                  0.0               0.0    1.659719e+09          0.000000   
...                ...               ...             ...               ...   
10039              0.0               0.0    1.549517e+00      26555.406249   
10040              0.0               0.0    2.108548e+00      35421.791380   
10041              0.0               0.0    8.152029e+00      43752.761110   
10042              0.0               0.0    1.564309e+00      26586.712659   
10043              0.0               0.0    1.103080e+00      44323.986387   

       label  
0        DoS  
1        DoS  
2        DoS  
3        DoS  
4        DoS  
...      ...  
10039  Torii  
10040  Torii  
10041  Torii  
10042  Torii  
10043  Torii  

[2348902 rows x 63 columns]

In [127]:
source_df = source_df.groupby('label').apply(lambda x: x.sample(n=10000)).reset_index(drop = True)
source_df

ts  flow_duration  Header_Length  Protocol Type  Duration  \
0      1.665260e+09       2.578546       543796.0            6.0      64.0   
1      1.665258e+09      48.683019      1101488.5            9.3     148.1   
2      1.665263e+09      97.456289      5352826.7            6.0     163.7   
3      1.665255e+09       3.603986       395090.5            6.0      80.8   
4      1.665254e+09      58.905617      2505642.3            6.0     133.6   
...             ...            ...            ...            ...       ...   
39995  1.538542e+09   17055.719306       395528.8            4.8      43.7   
39996  1.538522e+09    1187.460003        33768.1            6.0      56.5   
39997  1.538585e+09    9708.806346       229925.6            4.8      44.4   
39998  1.538631e+09   24006.005443       557827.0            6.0      56.0   
39999  1.538583e+09    8294.393578       178934.8            6.5      50.8   

             Rate       Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0      182.465697  182.465697    0.0              0.0              0.0  ...   
1       41.843644   41.843644    0.0              0.0              0.0  ...   
2       57.015111   57.015111    0.0              0.0              0.0  ...   
3      186.563518  186.563518    0.0              0.0              0.0  ...   
4       34.055903   34.055903    0.0              0.0              0.0  ...   
...           ...         ...    ...              ...              ...  ...   
39995    0.410353    0.410353    0.0              0.0              0.0  ...   
39996    0.418119    0.418119    0.0              0.0              0.0  ...   
39997    0.412377    0.412377    0.0              0.0              0.0  ...   
39998    0.410376    0.410376    0.0              0.0              0.0  ...   
39999    0.332413    0.332413    0.0              0.0              0.0  ...   

         Covariance  Variance  Weight  DS status  Fragments  Sequence number  \
0      4.833732e+05       1.0   244.6        0.0        0.0              0.0   
1      1.329967e+06       1.0   244.6        0.0        0.0              0.0   
2      1.505058e+06       1.0   244.6        0.0        0.0              0.0   
3      1.385937e+07       1.0   244.6        0.0        0.0              0.0   
4      8.543762e+05       1.0   244.6        0.0        0.0              0.0   
...             ...       ...     ...        ...        ...              ...   
39995  1.591972e+00       0.3    38.5        0.0        0.0              0.0   
39996  1.504052e+02       1.0   244.6        0.0        0.0              0.0   
39997  1.574009e+02       1.0   244.6        0.0        0.0              0.0   
39998  0.000000e+00       0.0    38.5        0.0        0.0              0.0   
39999  1.636440e+02       1.0   244.6        0.0        0.0              0.0   

       Protocol Version  flow_idle_time  flow_active_time   label  
0                   0.0    2.047896e-03          2.578546  Benign  
1                   0.0    1.665258e+08         48.683019  Benign  
2                   0.0    1.405141e-02         97.456289  Benign  
3                   0.0    4.301095e-03          3.603986  Benign  
4                   0.0    4.250660e-02         58.905617  Benign  
...                 ...             ...               ...     ...  
39995               0.0    2.084537e+00      17055.719306   Torii  
39996               0.0    2.244149e+00       1187.460003   Torii  
39997               0.0    2.078166e+00       9708.806346   Torii  
39998               0.0    2.587357e+00      24006.005443   Torii  
39999               0.0    2.867840e+01       8294.393578   Torii  

[40000 rows x 63 columns]

In [128]:
y = source_df["label"]

X = source_df.drop(['label'], axis = 1)

X_train_source, X_test_source, y_train_source, y_test_source = train_test_split(X, y, test_size=0.3) # 80% training and 30% test


In [129]:
y_test_source.value_counts()

Benign    3015
DoS       3001
Mirai     2995
Torii     2989
Name: label, dtype: int64

In [130]:
rf_source_domain =(RandomForestClassifier(n_estimators=100,oob_score=True))
t0 = time()
rf_source_domain = rf_source_domain.fit(X_train_source,y_train_source)
rf_source_predicted =rf_source_domain.predict(X_test_source)
accuracy = accuracy_score(y_test_source,rf_source_predicted)
#print (rf.oob_score_)
print ("Accuracy: ", accuracy)
#acc, score = rf.evaluate(x_test, y_test)
print("Time: ", time()-t0)   
# creating a confusion matrix 
rf_cm = confusion_matrix(y_test_source, rf_source_predicted)
print("Confusion Matrix: ", rf_cm)
print(classification_report(y_test_source, rf_source_predicted))


Accuracy:  1.0
Time:  1.5893990993499756
Confusion Matrix:  [[3015    0    0    0]
 [   0 3001    0    0]
 [   0    0 2995    0]
 [   0    0    0 2989]]
              precision    recall  f1-score   support

      Benign       1.00      1.00      1.00      3015
         DoS       1.00      1.00      1.00      3001
       Mirai       1.00      1.00      1.00      2995
       Torii       1.00      1.00      1.00      2989

    accuracy                           1.00     12000
   macro avg       1.00      1.00      1.00     12000
weighted avg       1.00      1.00      1.00     12000



In [131]:
df_cm = pd.DataFrame(rf_cm, columns=np.unique(y_test), index = np.unique(y_test))
df_cm.index.name = 'Actual'
df_cm.columns.name = 'Predicted'

In [132]:
df_cm

Predicted  Benign   DoS  Mirai  Torii
Actual                               
Benign       3015     0      0      0
DoS             0  3001      0      0
Mirai           0     0   2995      0
Torii           0     0      0   2989

In [133]:

fig = px.imshow(df_cm, text_auto=True, color_continuous_scale='Blues',)
fig.show()

In [ ]:
# Import necessary libraries
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression

# # Load your dataset and split it into features and labels
# X, y = load_your_dataset()

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# X_train_source, X_test_source, y_train_source, y_test_source 
# Initialize a list of models
models = [
    ('KNN', KNeighborsClassifier()),
    ('SVM', SVC()),
    ('Naive Bayes', GaussianNB()),
    ('Logistic Regression', LogisticRegression()),
    ('Decision Tree', DecisionTreeClassifier()),
    ('Random Forest', RandomForestClassifier()),
    ('Gradient Boosting', GradientBoostingClassifier()),
    ('K-Means', KMeans()),
    ('Linear Regression', LinearRegression())
]

# Initialize dictionaries to store results
accuracy_results = {}
classification_report_results = {}
confusion_matrix_results = {}
saved_models = {}

# Iterate through the models
for name, model in models:
    # Fit the model to the training data
    model.fit(X_train_source, y_train_source)
    
    # Save the fitted model
    joblib.dump(model, f"{name}_model.pkl")
    saved_models[name] = f"{name}_model.pkl"
    
    # Make predictions on the test data
    y_pred = model.predict(X_test_source.values)
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test_source, y_pred)
    accuracy_results[name] = accuracy
    
    # Generate a classification report
    class_report = classification_report(y_test_source, y_pred)
    classification_report_results[name] = class_report
    
    # Generate a confusion matrix
    conf_matrix = confusion_matrix(y_test_source, y_pred)
    confusion_matrix_results[name] = conf_matrix

# Print or visualize the results as needed
print("Accuracy Results:")
for name, accuracy in accuracy_results.items():
    print(f"{name}: {accuracy}")

print("\nClassification Report Results:")
for name, report in classification_report_results.items():
    print(f"{name}:\n{report}")

print("\nConfusion Matrix Results:")
for name, matrix in confusion_matrix_results.items():
    print(f"{name}:\n{matrix}")

# You can later load and use the saved models as needed
for name, model_file in saved_models.items():
    loaded_model = joblib.load(model_file)
    # Use loaded_model for predictions


In [156]:
from sklearn.ensemble import AdaBoostClassifier

from sklearn.ensemble import ExtraTreesClassifier

model_KNN = KNeighborsClassifier()
model_KNN = model_KNN.fit(X_train_source, y_train_source)

model_SVM = SVC()
model_SVM = model_SVM.fit(X_train_source, y_train_source)

model_NaiveBayes = GaussianNB()
model_NaiveBayes = model_NaiveBayes.fit(X_train_source, y_train_source)

model_LogisticRegression = LogisticRegression()
model_LogisticRegression = model_LogisticRegression.fit(X_train_source, y_train_source)

model_DecisionTree = DecisionTreeClassifier()
model_DecisionTree = model_DecisionTree.fit(X_train_source, y_train_source)

model_RandomForest = RandomForestClassifier()
model_RandomForest = model_RandomForest.fit(X_train_source, y_train_source)

model_GradientBoosting = GradientBoostingClassifier()
model_GradientBoosting = model_GradientBoosting.fit(X_train_source, y_train_source)

# model_KMeans = KMeans()
# model_KMeans = model_KMeans.fit(X_train_source, y_train_source)

model_ExtraTree = ExtraTreesClassifier()
model_ExtraTree = model_ExtraTree.fit(X_train_source, y_train_source)

model_AdaBoost = AdaBoostClassifier()
model_AdaBoost = model_AdaBoost.fit(X_train_source, y_train_source)

classifiers = [model_KNN,
            model_SVM,
            model_NaiveBayes,
            model_LogisticRegression,
            model_DecisionTree,
            model_RandomForest,
            model_GradientBoosting,
#             model_KMeans,
            model_ExtraTree,
            model_AdaBoost
              ]

for model in classifiers:
    # Fit the model to the training data
    y_pred = model.predict(X_test_source.values)
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test_source, y_pred)
    print(model)
    print(accuracy)
    cm = confusion_matrix(y_test_source, y_pred)
    print("Confusion Matrix: ", cm)
    print(classification_report(y_test_source, y_pred))
    df_cm = pd.DataFrame(cm, columns=np.unique(y_test_source), index = np.unique(y_test_source))
    df_cm.index.name = 'Actual'
    df_cm.columns.name = 'Predicted'
    fig = px.imshow(df_cm, text_auto=True, color_continuous_scale='Blues',)
    fig.show()

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but KNeighborsClassifier was fitted with feature names



KNeighborsClassifier()
0.63625
Confusion Matrix:  [[2035   19  778  183]
 [  40 2951   10    0]
 [1102   13 1069  811]
 [ 565    3  841 1580]]
              precision    recall  f1-score   support

      Benign       0.54      0.67      0.60      3015
         DoS       0.99      0.98      0.99      3001
       Mirai       0.40      0.36      0.38      2995
       Torii       0.61      0.53      0.57      2989

    accuracy                           0.64     12000
   macro avg       0.64      0.64      0.63     12000
weighted avg       0.64      0.64      0.63     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but SVC was fitted with feature names



SVC()
0.6590833333333334
Confusion Matrix:  [[2176  269  469  101]
 [   5 2996    0    0]
 [1112  153  965  765]
 [ 495   53  669 1772]]
              precision    recall  f1-score   support

      Benign       0.57      0.72      0.64      3015
         DoS       0.86      1.00      0.93      3001
       Mirai       0.46      0.32      0.38      2995
       Torii       0.67      0.59      0.63      2989

    accuracy                           0.66     12000
   macro avg       0.64      0.66      0.64     12000
weighted avg       0.64      0.66      0.64     12000



GaussianNB()
0.7540833333333333
Confusion Matrix:  [[2463  195  356    1]
 [   5 2996    0    0]
 [1468  110 1263  154]
 [ 620   42    0 2327]]
              precision    recall  f1-score   support

      Benign       0.54      0.82      0.65      3015
         DoS       0.90      1.00      0.94      3001
       Mirai       0.78      0.42      0.55      2995
       Torii       0.94      0.78      0.85      2989

    accuracy                           0.75     12000
   macro avg       0.79      0.75      0.75     12000
weighted avg       0.79      0.75      0.75     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but GaussianNB was fitted with feature names



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but LogisticRegression was fitted with feature names



LogisticRegression()
0.6814166666666667
Confusion Matrix:  [[2313  111  509   82]
 [  10 2991    0    0]
 [1153   84 1083  675]
 [ 471   26  702 1790]]
              precision    recall  f1-score   support

      Benign       0.59      0.77      0.66      3015
         DoS       0.93      1.00      0.96      3001
       Mirai       0.47      0.36      0.41      2995
       Torii       0.70      0.60      0.65      2989

    accuracy                           0.68     12000
   macro avg       0.67      0.68      0.67     12000
weighted avg       0.67      0.68      0.67     12000



DecisionTreeClassifier()
1.0
Confusion Matrix:  [[3015    0    0    0]
 [   0 3001    0    0]
 [   0    0 2995    0]
 [   0    0    0 2989]]
              precision    recall  f1-score   support

      Benign       1.00      1.00      1.00      3015
         DoS       1.00      1.00      1.00      3001
       Mirai       1.00      1.00      1.00      2995
       Torii       1.00      1.00      1.00      2989

    accuracy                           1.00     12000
   macro avg       1.00      1.00      1.00     12000
weighted avg       1.00      1.00      1.00     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but RandomForestClassifier was fitted with feature names



RandomForestClassifier()
1.0
Confusion Matrix:  [[3015    0    0    0]
 [   0 3001    0    0]
 [   0    0 2995    0]
 [   0    0    0 2989]]
              precision    recall  f1-score   support

      Benign       1.00      1.00      1.00      3015
         DoS       1.00      1.00      1.00      3001
       Mirai       1.00      1.00      1.00      2995
       Torii       1.00      1.00      1.00      2989

    accuracy                           1.00     12000
   macro avg       1.00      1.00      1.00     12000
weighted avg       1.00      1.00      1.00     12000



GradientBoostingClassifier()
1.0


/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names



Confusion Matrix:  [[3015    0    0    0]
 [   0 3001    0    0]
 [   0    0 2995    0]
 [   0    0    0 2989]]
              precision    recall  f1-score   support

      Benign       1.00      1.00      1.00      3015
         DoS       1.00      1.00      1.00      3001
       Mirai       1.00      1.00      1.00      2995
       Torii       1.00      1.00      1.00      2989

    accuracy                           1.00     12000
   macro avg       1.00      1.00      1.00     12000
weighted avg       1.00      1.00      1.00     12000



ExtraTreesClassifier()
1.0
Confusion Matrix:  [[3015    0    0    0]
 [   0 3001    0    0]
 [   0    0 2995    0]
 [   0    0    0 2989]]


/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names



              precision    recall  f1-score   support

      Benign       1.00      1.00      1.00      3015
         DoS       1.00      1.00      1.00      3001
       Mirai       1.00      1.00      1.00      2995
       Torii       1.00      1.00      1.00      2989

    accuracy                           1.00     12000
   macro avg       1.00      1.00      1.00     12000
weighted avg       1.00      1.00      1.00     12000



AdaBoostClassifier()
0.74875
Confusion Matrix:  [[   0 3015    0    0]
 [   0 3001    0    0]
 [   0    0 2995    0]
 [   0    0    0 2989]]


/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but AdaBoostClassifier was fitted with feature names

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      3015
         DoS       0.50      1.00      0.67      3001
       Mirai       1.00      1.00      1.00      2995
       Torii       1.00      1.00      1.00      2989

    accuracy                           0.75     12000
   macro avg       0.62      0.75      0.67     12000
weighted avg       0.62      0.75      0.67     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



# Target

In [161]:
path = r'/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/medbiotMalware/dos' # use your path
all_files = glob.glob(path + "/*.csv")
li = []

for filename in all_files:
    df = pd.read_csv(filename)
    li.append(df)

dos_df = pd.concat(li, axis=0, ignore_index=True)
dos_df['label'] = 'DoS'

dos_df.head()



ts  flow_duration  Header_Length  Protocol Type  Duration  \
0  1.559706e+09       0.043192          617.8            8.2      79.2   
1  1.559706e+09       0.201874         1075.0           12.6      67.8   
2  1.559706e+09       0.023036         1255.0           15.9      71.3   
3  1.559706e+09       0.054716         1446.0           13.7     151.7   
4  1.559706e+09       0.149081          295.4            8.2     189.2   

          Rate        Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0   295.809663   295.809663    0.0              0.0              0.2  ...   
1  1592.273253  1592.273253    0.0              0.0              0.0  ...   
2   197.286607   197.286607    0.0              0.1              0.0  ...   
3  3449.831947  3449.831947    0.0              0.1              0.0  ...   
4  3730.665751  3730.665751    0.0              0.3              0.0  ...   

      Covariance  Variance  Weight  DS status  Fragments  Sequence number  \
0   25166.945164       0.9    38.5        0.0        0.0              0.0   
1   87502.610867       1.0   244.6        0.0        0.0              0.0   
2  249950.406176       0.9    38.5        0.0        0.0              0.0   
3  267810.951088       1.0   244.6        0.0        0.0              0.0   
4     544.028628       0.9    38.5        0.0        0.0              0.0   

   Protocol Version  flow_idle_time  flow_active_time  label  
0               0.0    3.119411e+08          0.043192    DoS  
1               0.0    3.119411e+08          0.201874    DoS  
2               0.0    3.119411e+08          0.023036    DoS  
3               0.0    3.119411e+08          0.054716    DoS  
4               0.0    1.559706e+08          0.149081    DoS  

[5 rows x 63 columns]

In [162]:
path = r'/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/medbiotMalware/mirai' # use your path
all_files = glob.glob(path + "/*.csv")
li = []

for filename in all_files:
    df = pd.read_csv(filename)
    li.append(df)

mirai_df = pd.concat(li, axis=0, ignore_index=True)
mirai_df['label'] = 'Mirai'

mirai_df.head()



ts  flow_duration  Header_Length  Protocol Type  Duration  \
0  1.564040e+09       0.000031          100.1           17.0     128.0   
1  1.564040e+09       0.000127          102.7           17.0     128.0   
2  1.564040e+09       0.001080          150.2           12.6     102.4   
3  1.564040e+09       0.005885          342.5           15.9     120.1   
4  1.564040e+09       0.009758          663.6           14.8     102.4   

            Rate          Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0  420079.673065  420079.673065    0.0              0.0              0.0  ...   
1    6247.470405    6247.470405    0.0              0.0              0.0  ...   
2    6936.219502    6936.219502    0.0              0.0              0.0  ...   
3     426.654419     426.654419    0.0              0.0              0.0  ...   
4    1385.023944    1385.023944    0.0              0.0              0.0  ...   

      Covariance  Variance  Weight  DS status  Fragments  Sequence number  \
0       0.000000       0.0    38.5        0.0        0.0              0.0   
1       6.960125       0.3   244.6        0.0        0.0              0.0   
2    2221.611603       0.5    38.5        0.0        0.0              0.0   
3    7148.602501       1.0   244.6        0.0        0.0              0.0   
4  273735.155694       0.9    38.5        0.0        0.0              0.0   

   Protocol Version  flow_idle_time  flow_active_time  label  
0               0.0    1.094828e+09          0.000031  Mirai  
1               0.0    9.384237e+08          0.000127  Mirai  
2               0.0    9.384237e+08          0.001080  Mirai  
3               0.0    1.564040e+08          0.005885  Mirai  
4               0.0    6.256158e+08          0.009758  Mirai  

[5 rows x 63 columns]

In [163]:
torii_df = pd.read_csv('/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/medbiotMalware/torii_mal_all.csv')
torii_df['label']='Torii'
torii_df



ts  flow_duration  Header_Length  Protocol Type  Duration  \
0      1.552735e+09       0.399095       3538.400            6.0    56.200   
1      1.552735e+09       9.217073       8731.000            6.0    57.600   
2      1.552735e+09      34.655652       9271.000            6.0    56.000   
3      1.552735e+09      60.576496       9811.000            6.0    56.000   
4      1.552735e+09      86.517244      10351.000            6.0    56.000   
...             ...            ...            ...            ...       ...   
32173  1.552847e+09   24227.207885     554833.900            6.0    54.200   
32174  1.552847e+09   24230.588614     554691.000            6.0    55.900   
32175  1.552847e+09   24234.750599     554755.800            6.0    55.800   
32176  1.552847e+09   24237.495373     554969.500            6.0    52.700   
32177  1.552847e+09   24244.375182     554927.875            6.0    47.625   

            Rate      Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0      15.695348  15.695348    0.0              0.0              0.2  ...   
1       5.089644   5.089644    0.0              0.0              0.0  ...   
2       0.756723   0.756723    0.0              0.0              0.0  ...   
3       0.589819   0.589819    0.0              0.0              0.0  ...   
4       0.527243   0.527243    0.0              0.0              0.0  ...   
...          ...        ...    ...              ...              ...  ...   
32173   0.410043   0.410043    0.0              0.0              0.0  ...   
32174   0.409969   0.409969    0.0              0.0              0.0  ...   
32175   0.409949   0.409949    0.0              0.0              0.0  ...   
32176   0.410018   0.410018    0.0              0.0              0.0  ...   
32177   0.409899   0.409899    0.0              0.0              0.0  ...   

          Covariance  Variance  Weight  DS status  Fragments  Sequence number  \
0      304022.657408       0.9    38.5        0.0        0.0              0.0   
1      410597.194335       1.0   244.6        0.0        0.0              0.0   
2           0.000000       0.0    38.5        0.0        0.0              0.0   
3           0.000000       0.0   244.6        0.0        0.0              0.0   
4           0.000000       0.0    38.5        0.0        0.0              0.0   
...              ...       ...     ...        ...        ...              ...   
32173     151.499476       0.6    38.5        0.0        0.0              0.0   
32174     158.276056       1.0   244.6        0.0        0.0              0.0   
32175       0.000000       0.0    38.5        0.0        0.0              0.0   
32176       0.000000       0.0   244.6        0.0        0.0              0.0   
32177       0.000000       0.0    25.5        0.0        0.0              0.0   

       Protocol Version  flow_idle_time  flow_active_time  label  
0                   0.0    1.552735e+08          0.399095  Torii  
1                   0.0    2.077400e+00          9.217073  Torii  
2                   0.0    2.594263e+00         34.655652  Torii  
3                   0.0    2.592883e+00         60.576496  Torii  
4                   0.0    2.594634e+00         86.517244  Torii  
...                 ...             ...               ...    ...  
32173               0.0    2.260242e+00      24227.207885  Torii  
32174               0.0    2.573863e+00      24230.588614  Torii  
32175               0.0    2.596845e+00      24234.750599  Torii  
32176               0.0    3.642468e+00      24237.495373  Torii  
32177               0.0    5.037822e+00      24244.375182  Torii  

[32178 rows x 63 columns]

In [164]:
path = r'/Users/priscilladanso/Documents/Stony Brook/CSE 509 Network Security/supplementary_materials/pcap2csv/medbiotMalware/benign' # use your path
all_files = glob.glob(path + "/*.csv")
li = []

for filename in all_files:
    df = pd.read_csv(filename)
    li.append(df)

benign_df = pd.concat(li, axis=0, ignore_index=True)

benign_df['label']='Benign'
benign_df


ts  flow_duration  Header_Length  Protocol Type  Duration  \
0       1.526072e+09       0.261976          176.8            7.1      50.5   
1       1.526072e+09       0.454541          341.4            7.1      58.6   
2       1.526072e+09       0.616774          412.4            6.0      55.0   
3       1.526072e+09       0.495016          280.5            7.1      50.6   
4       1.526072e+09       0.486373          373.2            6.0      57.0   
...              ...            ...            ...            ...       ...   
168632  1.526022e+09       4.809286          193.8            9.3      64.0   
168633  1.526022e+09       4.711348          158.8            7.0      51.2   
168634  1.526022e+09       4.408196          186.4            9.3      64.0   
168635  1.526022e+09    4772.508785        13289.8           10.4      63.3   
168636  1.526022e+09       2.001557          136.0           12.6      64.0   

              Rate       Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0         3.877643    3.877643    0.0              0.0              0.4  ...   
1         9.984625    9.984625    0.0              0.2              0.3  ...   
2         8.949259    8.949259    0.0              0.2              0.2  ...   
3       705.027620  705.027620    0.0              0.1              0.2  ...   
4        10.638198   10.638198    0.0              0.1              0.2  ...   
...            ...         ...    ...              ...              ...  ...   
168632    0.914302    0.914302    0.0              0.0              0.7  ...   
168633    1.167562    1.167562    0.0              0.0              0.6  ...   
168634    1.024321    1.024321    0.0              0.0              0.7  ...   
168635    1.030487    1.030487    0.0              0.0              0.6  ...   
168636    0.780782    0.780782    0.0              0.0              0.4  ...   

         Covariance  Variance  Weight  DS status  Fragments  Sequence number  \
0        228.620380       0.8    38.5        0.0        0.0              0.0   
1       1231.487783       1.0   244.6        0.0        0.0              0.0   
2       2807.699476       0.9    38.5        0.0        0.0              0.0   
3       1499.904916       1.0   244.6        0.0        0.0              0.0   
4         64.017143       0.9    38.5        0.0        0.0              0.0   
...             ...       ...     ...        ...        ...              ...   
168632    64.629932       0.8    38.5        0.0        0.0              0.0   
168633    78.963786       1.0   244.6        0.0        0.0              0.0   
168634    75.854623       0.9    38.5        0.0        0.0              0.0   
168635   111.224169       1.0   244.6        0.0        0.0              0.0   
168636    76.977778       0.8    11.0        0.0        0.0              0.0   

        Protocol Version  flow_idle_time  flow_active_time   label  
0                    0.0    7.630360e+08          0.261976  Benign  
1                    0.0    4.578216e+08          0.454541  Benign  
2                    0.0    1.526072e+08          0.616774  Benign  
3                    0.0    4.578216e+08          0.495016  Benign  
4                    0.0    1.526072e+08          0.486373  Benign  
...                  ...             ...               ...     ...  
168632               0.0    6.104090e+08          4.809286  Benign  
168633               0.0    4.578067e+08          4.711348  Benign  
168634               0.0    6.104090e+08          4.408196  Benign  
168635               0.0    4.578067e+08       4772.508785  Benign  
168636               0.0    9.156134e+08          2.001557  Benign  

[168637 rows x 63 columns]

In [165]:
print(dos_df.shape,
    miriai_df.shape,
    benign_df.shape, 
    torii_df.shape)

(3478, 63) (150442, 63) (168637, 63) (32178, 63)


In [166]:
target_data = [
    dos_df,
    miriai_df,
    benign_df, 
    torii_df,
]

target_df = pd.concat(target_data)
target_df = target_df.groupby('label').apply(lambda x: x.sample(n=3000)).reset_index(drop = True)
target_df

ts  flow_duration  Header_Length  Protocol Type  Duration  \
0      1.525922e+09       4.507455          179.0            9.3      64.0   
1      1.525919e+09       4.708138          190.4            5.9      51.2   
2      1.526133e+09       3.203223          171.6            9.3      64.0   
3      1.526250e+09       1.801458          112.4            7.6      51.2   
4      1.526042e+09       2.201275          158.8            8.2      64.0   
...             ...            ...            ...            ...       ...   
11995  1.552841e+09   18276.207978       418178.0            6.0      55.9   
11996  1.552751e+09   15233.530327       357061.7            6.0      55.6   
11997  1.552817e+09   39182.082019       897068.8            6.0      55.9   
11998  1.552839e+09   15968.444659       365417.1            6.0      55.8   
11999  1.552760e+09   24192.163761       562078.8            6.0      54.0   

           Rate     Srate  Drate  fin_flag_number  syn_flag_number  ...  \
0      0.880982  0.880982    0.0              0.0              0.7  ...   
1      0.838034  0.838034    0.0              0.0              0.7  ...   
2      1.091159  1.091159    0.0              0.0              0.7  ...   
3      1.172197  1.172197    0.0              0.0              0.4  ...   
4      1.515587  1.515587    0.0              0.0              0.8  ...   
...         ...       ...    ...              ...              ...  ...   
11995  0.409850  0.409850    0.0              0.0              0.0  ...   
11996  0.411002  0.411002    0.0              0.0              0.0  ...   
11997  0.409996  0.409996    0.0              0.0              0.0  ...   
11998  0.409877  0.409877    0.0              0.0              0.0  ...   
11999  0.410563  0.410563    0.0              0.0              0.0  ...   

       Covariance  Variance  Weight  DS status  Fragments  Sequence number  \
0       95.607404       1.0   244.6        0.0        0.0              0.0   
1       27.668820       0.5    38.5        0.0        0.0              0.0   
2       68.864532       1.0   244.6        0.0        0.0              0.0   
3      157.098491       1.0   244.6        0.0        0.0              0.0   
4       34.542095       0.6    38.5        0.0        0.0              0.0   
...           ...       ...     ...        ...        ...              ...   
11995    0.000000       0.0   244.6        0.0        0.0              0.0   
11996    0.000000       0.0    38.5        0.0        0.0              0.0   
11997    0.000000       0.0    38.5        0.0        0.0              0.0   
11998    0.000000       0.0   244.6        0.0        0.0              0.0   
11999  126.712081       0.5    38.5        0.0        0.0              0.0   

       Protocol Version  flow_idle_time  flow_active_time   label  
0                   0.0    7.629611e+08          4.507455  Benign  
1                   0.0    1.525919e+08          4.708138  Benign  
2                   0.0    6.104530e+08          3.203223  Benign  
3                   0.0    4.578749e+08          1.801458  Benign  
4                   0.0    6.104170e+08          2.201275  Benign  
...                 ...             ...               ...     ...  
11995               0.0    2.594209e+00      18276.207978   Torii  
11996               0.0    2.594890e+00      15233.530327   Torii  
11997               0.0    2.594658e+00      39182.082019   Torii  
11998               0.0    2.604619e+00      15968.444659   Torii  
11999               0.0    9.259818e-01      24192.163761   Torii  

[12000 rows x 63 columns]

In [167]:
target_df.columns

Index(['ts', 'flow_duration', 'Header_Length', 'Protocol Type', 'Duration',
       'Rate', 'Srate', 'Drate', 'fin_flag_number', 'syn_flag_number',
       'rst_flag_number', 'psh_flag_number', 'ack_flag_number',
       'urg_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count',
       'syn_count', 'fin_count', 'urg_count', 'rst_count', 'max_duration',
       'min_duration', 'sum_duration', 'average_duration', 'std_duration',
       'CoAP', 'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP',
       'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min',
       'Max', 'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'MAC', 'Magnitue',
       'Radius', 'Covariance', 'Variance', 'Weight', 'DS status', 'Fragments',
       'Sequence number', 'Protocol Version', 'flow_idle_time',
       'flow_active_time', 'label'],
      dtype='object')

In [168]:
y = target_df["label"]

X = target_df.drop(['label'], axis = 1)

X_train_target, X_test_target, y_train_target, y_test_target = train_test_split(X, y, test_size=0.3) # 70% training and 30% test
rf_target_domain =(RandomForestClassifier(n_estimators=100,oob_score=True))
t0 = time()
rf_target_domain = rf_target_domain.fit(X_train_target,y_train_target)
rf_target_predicted =rf_target_domain.predict(X_test_target)
accuracy = accuracy_score(y_test_target,rf_target_predicted)
#print (rf.oob_score_)
print ("Accuracy: ", accuracy)
#acc, score = rf.evaluate(x_test, y_test)
print("Time: ", time()-t0)   
# creating a confusion matrix 
rf_cm = confusion_matrix(y_test_target, rf_target_predicted)
print("Confusion Matrix: ", rf_cm)
print(classification_report(y_test_target, rf_target_predicted))


Accuracy:  1.0
Time:  0.47067713737487793
Confusion Matrix:  [[941   0   0   0]
 [  0 877   0   0]
 [  0   0 889   0]
 [  0   0   0 893]]
              precision    recall  f1-score   support

      Benign       1.00      1.00      1.00       941
         DoS       1.00      1.00      1.00       877
       Mirai       1.00      1.00      1.00       889
       Torii       1.00      1.00      1.00       893

    accuracy                           1.00      3600
   macro avg       1.00      1.00      1.00      3600
weighted avg       1.00      1.00      1.00      3600



In [169]:
df_cm = pd.DataFrame(rf_cm, columns=np.unique(y_test_target), index = np.unique(y_test_target))
df_cm.index.name = 'Actual'
df_cm.columns.name = 'Predicted'
fig = px.imshow(df_cm, text_auto=True, color_continuous_scale='Blues',)
fig.show()

In [170]:
rf_cross_predicted =rf_source_domain.predict(X)
accuracy = accuracy_score(y_test_source,rf_cross_predicted)
#print (rf.oob_score_)
print ("Accuracy: ", accuracy)
#acc, score = rf.evaluate(x_test, y_test)
print("Time: ", time()-t0)   
# creating a confusion matrix 
rf_cm = confusion_matrix(y_test_source, rf_cross_predicted)
print("Confusion Matrix: ", rf_cm)
print(classification_report(y_test_source, rf_cross_predicted))

df_cm = pd.DataFrame(rf_cm, columns=np.unique(y_test_source), index = np.unique(y_test_source))
df_cm.index.name = 'Actual'
df_cm.columns.name = 'Predicted'
fig = px.imshow(df_cm, text_auto=True, color_continuous_scale='Blues',)
fig.show()

Accuracy:  0.25083333333333335
Time:  1.1115291118621826
Confusion Matrix:  [[   0    0  779 2236]
 [   0    0  732 2269]
 [   0    0  755 2240]
 [   0    0  734 2255]]
              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      3015
         DoS       0.00      0.00      0.00      3001
       Mirai       0.25      0.25      0.25      2995
       Torii       0.25      0.75      0.38      2989

    accuracy                           0.25     12000
   macro avg       0.13      0.25      0.16     12000
weighted avg       0.13      0.25      0.16     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [171]:
for model in classifiers:
    # Fit the model to the training data
    y_pred = model.predict(X.values)
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test_source, y_pred)
    print(model)
    print(accuracy)
    cm = confusion_matrix(y_test_source, y_pred)
    print("Confusion Matrix: ", cm)
    print(classification_report(y_test_source, y_pred))
    df_cm = pd.DataFrame(cm, columns=np.unique(y_test_source), index = np.unique(y_test_source))
    df_cm.index.name = 'Actual'
    df_cm.columns.name = 'Predicted'
    fig = px.imshow(df_cm, text_auto=True, color_continuous_scale='Blues',)
    fig.show()

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but KNeighborsClassifier was fitted with feature names



KNeighborsClassifier()
0.25
Confusion Matrix:  [[ 668  341  504 1502]
 [ 694  349  489 1469]
 [ 644  370  498 1483]
 [ 687  318  499 1485]]
              precision    recall  f1-score   support

      Benign       0.25      0.22      0.23      3015
         DoS       0.25      0.12      0.16      3001
       Mirai       0.25      0.17      0.20      2995
       Torii       0.25      0.50      0.33      2989

    accuracy                           0.25     12000
   macro avg       0.25      0.25      0.23     12000
weighted avg       0.25      0.25      0.23     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but SVC was fitted with feature names



SVC()
0.24925
Confusion Matrix:  [[ 465 1511  384  655]
 [ 468 1520  381  632]
 [ 435 1510  362  688]
 [ 457 1500  388  644]]
              precision    recall  f1-score   support

      Benign       0.25      0.15      0.19      3015
         DoS       0.25      0.51      0.34      3001
       Mirai       0.24      0.12      0.16      2995
       Torii       0.25      0.22      0.23      2989

    accuracy                           0.25     12000
   macro avg       0.25      0.25      0.23     12000
weighted avg       0.25      0.25      0.23     12000



GaussianNB()
0.2540833333333333
Confusion Matrix:  [[ 599 1491  315  610]
 [ 604 1503  286  608]
 [ 558 1499  320  618]
 [ 596 1485  281  627]]
              precision    recall  f1-score   support

      Benign       0.25      0.20      0.22      3015
         DoS       0.25      0.50      0.33      3001
       Mirai       0.27      0.11      0.15      2995
       Torii       0.25      0.21      0.23      2989

    accuracy                           0.25     12000
   macro avg       0.26      0.25      0.24     12000
weighted avg       0.26      0.25      0.24     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but GaussianNB was fitted with feature names



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but LogisticRegression was fitted with feature names



LogisticRegression()
0.24941666666666668
Confusion Matrix:  [[ 517 1439  434  625]
 [ 517 1452  422  610]
 [ 472 1458  402  663]
 [ 485 1451  431  622]]
              precision    recall  f1-score   support

      Benign       0.26      0.17      0.21      3015
         DoS       0.25      0.48      0.33      3001
       Mirai       0.24      0.13      0.17      2995
       Torii       0.25      0.21      0.23      2989

    accuracy                           0.25     12000
   macro avg       0.25      0.25      0.23     12000
weighted avg       0.25      0.25      0.23     12000



DecisionTreeClassifier()
0.25083333333333335
Confusion Matrix:  [[   0    0  779 2236]
 [   0    0  732 2269]
 [   0    0  755 2240]
 [   0    0  734 2255]]
              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      3015
         DoS       0.00      0.00      0.00      3001
       Mirai       0.25      0.25      0.25      2995
       Torii       0.25      0.75      0.38      2989

    accuracy                           0.25     12000
   macro avg       0.13      0.25      0.16     12000
weighted avg       0.13      0.25      0.16     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parame

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but RandomForestClassifier was fitted with feature names



RandomForestClassifier()
0.25083333333333335


/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



Confusion Matrix:  [[   0    0  779 2236]
 [   0    0  732 2269]
 [   0    0  755 2240]
 [   0    0  734 2255]]
              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      3015
         DoS       0.00      0.00      0.00      3001
       Mirai       0.25      0.25      0.25      2995
       Torii       0.25      0.75      0.38      2989

    accuracy                           0.25     12000
   macro avg       0.13      0.25      0.16     12000
weighted avg       0.13      0.25      0.16     12000



GradientBoostingClassifier()
0.25083333333333335
Confusion Matrix:  [[   0    0  779 2236]
 [   0    0  732 2269]
 [   0    0  755 2240]
 [   0    0  734 2255]]


/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      3015
         DoS       0.00      0.00      0.00      3001
       Mirai       0.25      0.25      0.25      2995
       Torii       0.25      0.75      0.38      2989

    accuracy                           0.25     12000
   macro avg       0.13      0.25      0.16     12000
weighted avg       0.13      0.25      0.16     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names



ExtraTreesClassifier()
0.25083333333333335
Confusion Matrix:  [[   0    0  779 2236]
 [   0    0  732 2269]
 [   0    0  755 2240]
 [   0    0  734 2255]]


/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      3015
         DoS       0.00      0.00      0.00      3001
       Mirai       0.25      0.25      0.25      2995
       Torii       0.25      0.75      0.38      2989

    accuracy                           0.25     12000
   macro avg       0.13      0.25      0.16     12000
weighted avg       0.13      0.25      0.16     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



AdaBoostClassifier()
0.25083333333333335
Confusion Matrix:  [[   0    0  779 2236]
 [   0    0  732 2269]
 [   0    0  755 2240]
 [   0    0  734 2255]]


/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning:

X does not have valid feature names, but AdaBoostClassifier was fitted with feature names

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



              precision    recall  f1-score   support

      Benign       0.00      0.00      0.00      3015
         DoS       0.00      0.00      0.00      3001
       Mirai       0.25      0.25      0.25      2995
       Torii       0.25      0.75      0.38      2989

    accuracy                           0.25     12000
   macro avg       0.13      0.25      0.16     12000
weighted avg       0.13      0.25      0.16     12000



/Users/priscilladanso/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

